export const MENU = [
  { text: "use-reducer", link: "/use-reducer" },
  { text: "gsap-animations", link: "/gsap-animations" },
  { text: "gsap-scroll", link: "/gsap-scroll" },
  { text: "test-api", link: "/test-api" },
  { text: "adaptive-flex", link: "/adaptive-flex" },
  { text: "animations-text", link: "/animations-text" },
  { text: "text", link: "/text" },
  { text: "popper/floating", link: "/popper" },
  { text: "parallax", link: "/parallax" },
  { text: "radix", link: "/radix" },
  { text: "imperative-handle", link: "/imperative-handle" },
  { text: "anim1", link: "/anim1" },
  { text: "other", link: "/other" },
];
